# Generated by Django 3.2 on 2021-12-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='item_size',
            new_name='size',
        ),
    ]
