# Generated by Django 3.2 on 2022-01-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='one_star',
        ),
    ]
