# Generated by Django 3.2 on 2022-01-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_rating_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
