# Generated by Django 3.2 on 2021-12-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_friendly_name_category_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='default_image', null=True, upload_to=''),
        ),
    ]
