# Generated by Django 3.2 on 2022-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='one_star',
            field=models.IntegerField(default=0),
        ),
    ]
