# Generated by Django 3.2 on 2022-01-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
