# Generated by Django 3.2 on 2022-01-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_rating_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='name',
        ),
    ]
