# Generated by Django 3.2 on 2022-01-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_rating_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='two_stars',
            field=models.IntegerField(default=0),
        ),
    ]
