# Generated by Django 3.2 on 2022-01-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
