# Generated by Django 3.2 on 2022-01-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_rating_two_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_total',
            field=models.IntegerField(default=0),
        ),
    ]
