# Generated by Django 3.2 on 2022-01-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_item_rating_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating_total',
        ),
    ]
