# Generated by Django 3.2 on 2022-01-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_remove_rating_rating_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='rating',
            name='one_star',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='two_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
