# Generated by Django 3.2 on 2022-01-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20220106_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rating_total',
        ),
    ]
