# Generated by Django 3.2 on 2022-01-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_item_rating_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='five_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='four_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='three_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
